[package]
name = "church_sound"
version = "0.1.0"
authors = ["Joe Tennies <joe@fatnsoft.com>"]

[dependencies]
gstreamer = "0.12.2"
gio = "0.5.0"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_10"]
